import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const appDir = path.resolve(scriptDir, "..");
const snapshotPath = path.join(
  appDir,
  "lib/constants/landing-page/generated.ts",
);

async function loadEnvFile(filePath: string) {
  try {
    const contents = await readFile(filePath, "utf8");
    for (const rawLine of contents.split(/\r?\n/)) {
      const line = rawLine.trim();
      if (!line || line.startsWith("#")) continue;

      const normalizedLine = line.startsWith("export ")
        ? line.slice("export ".length).trim()
        : line;
      const separatorIndex = normalizedLine.indexOf("=");
      if (separatorIndex === -1) continue;

      const key = normalizedLine.slice(0, separatorIndex).trim();
      const rawValue = normalizedLine.slice(separatorIndex + 1).trim();
      const value = rawValue.replace(/^(['"])(.*)\1$/, "$2");
      process.env[key] = value;
    }
  } catch (error: any) {
    if (error?.code !== "ENOENT") {
      throw error;
    }
  }
}

await loadEnvFile(path.join(appDir, ".env"));
await loadEnvFile(path.join(appDir, ".env.local"));

const { fetchLandingPageData } =
  await import("../lib/functions/fetchLandingPageDataFromNotion");

function isTemporaryNotionFileUrl(value: string) {
  try {
    const url = new URL(value);
    return (
      url.hostname === "prod-files-secure.s3.us-west-2.amazonaws.com" &&
      url.searchParams.has("X-Amz-Signature")
    );
  } catch {
    return false;
  }
}

function fallbackForTemporaryFileUrl(pathParts: string[]) {
  const key = pathParts[pathParts.length - 1];
  const pathName = pathParts.join(".");

  if (key === "logo" || key === "darkLogo") {
    return "/logo.png";
  }

  if (key === "imageUrl" && pathName.includes("teamSection.teamList")) {
    return "/anoop.jpg";
  }

  return "";
}

function sanitizeSnapshotValue(
  value: unknown,
  pathParts: string[] = [],
): unknown {
  if (typeof value === "string") {
    return isTemporaryNotionFileUrl(value)
      ? fallbackForTemporaryFileUrl(pathParts)
      : value;
  }

  if (Array.isArray(value)) {
    return value.map((item, index) =>
      sanitizeSnapshotValue(item, [...pathParts, String(index)]),
    );
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [
        key,
        sanitizeSnapshotValue(item, [...pathParts, key]),
      ]),
    );
  }

  return value;
}

const landingPageData = sanitizeSnapshotValue(await fetchLandingPageData());
const syncedAt = new Date().toISOString();

const fileContents = `/* eslint-disable */
/*
 * Generated by \`pnpm --filter web sync:cms-constants\`.
 * Do not edit this file by hand. Admin/CMS changes should be synced by rerunning the command.
 */

export const landingPageSnapshotSyncedAt = ${JSON.stringify(syncedAt)};

export const landingPageSnapshot: any = ${JSON.stringify(landingPageData, null, 2)};
`;

await mkdir(path.dirname(snapshotPath), { recursive: true });
await writeFile(snapshotPath, fileContents);

console.log(`Synced CMS landing constants to ${snapshotPath}`);
console.log(`Snapshot timestamp: ${syncedAt}`);
