/* eslint-disable */
/*
 * Generated by `pnpm --filter web sync:cms-constants`.
 * Do not edit this file by hand. Admin/CMS changes should be synced by rerunning the command.
 */

export const landingPageSnapshotSyncedAt = "2026-09-04T04:41:32.041Z";

export const landingPageSnapshot: any = {
  "navbarSection": {
    "title": "Bayesian Labs",
    "logo": "/logo.png",
    "darkLogo": "/logo.png",
    "githubLink": "https://github.com/anoopkarnik/company-landing-page",
    "githubUsername": "anoopkarnik",
    "githubRepositoryName": "company-landing-page",
    "donateNowLink": ""
  },
  "heroSection": {
    "tagline": "AI automation and production-ready products, built end-to-end",
    "description": "Turn a manual workflow or product idea into a reliable deployed system—from discovery and architecture through implementation, launch, and handover.",
    "appointmentLink": "https://calendly.com/anoop-karnik-bayesian-labs/discovery-call",
    "codeSnippet": ""
  },
  "aboutSection": {
    "heading": "About",
    "companyDetails": "Bayesian Labs s a solopreneur-driven company specializing in Notion templates, open-source projects, and Micro SaaS products. Our mission is to bring automation and AI-driven efficiency to both businesses and individuals. We take ideas from concept to production—building small-scale projects (those that can be completed in under a month) from scratch with speed and quality. Each member of our team wears multiple hats, combining the expertise of a Project Manager, Full-Stack Developer, UI/UX Designer, QA Engineer, and DevOps Engineer. While we may not have the hyper-specialization of a dedicated team in each role, our depth of knowledge across these areas ensures timely execution with high-quality results. projects - from scratch to production. Each person part of the company has skills of a project manager, full stack developer, UI/UX designer, QA Engineer and Devops engineer. Our breadth in each of the above areas is not as good as a specialist but depth in each area is good enough to get the job done in a timely manner with quality.\n",
    "users": "8000",
    "subscribers": "16",
    "products": "16",
    "downloads": "7000"
  },
  "serviceSection": {
    "heading": "Client-Centric Services\n",
    "description": "These are some of the services that I offer to my clients. I am always looking to improve and add more services\n",
    "services": [
      {
        "id": "cmth6ypjf0001uon6sfr5i5lk",
        "title": "n8n Workflows",
        "description": "The support modules consists of documentation, newsletter to subscribe, send mail to our support and booking a discovery call with us using resend for mails and n8n workflows for ai assistant\n",
        "imageUrl": ""
      },
      {
        "id": "cmth6yplv0003uon6fpkaazfa",
        "title": "Notion Template Creation",
        "description": "The CMS Module use notion databases  through api and upstash redis for cache to get all data in landing pages\n",
        "imageUrl": ""
      },
      {
        "id": "cmth6ypn00005uon61bxrip7q",
        "title": "MVP Develpment",
        "description": "Landing Page Module consists of landing page with various sections (navbar, hero, feature, faq, pricing, footer), legal pages (contact us, cancellations & refund policies, privacy policy, terms & conditions). All these pages use shadcn, aceternity and custom components, blocks and themes.\n",
        "imageUrl": ""
      },
      {
        "id": "cmth6ypo40007uon688i1e9sr",
        "title": "AI Integration",
        "description": "A high-performance build system for SaaS Web Apps, which can be deployed immediately to vercel after just filling the environment variables\n",
        "imageUrl": ""
      }
    ]
  },
  "projectSection": {
    "heading": "Many Great Products\n",
    "description": "These are some of the products that we have build. We are always looking to improve and add more products\n",
    "projects": [
      {
        "id": "cmtikvteh0007uotxuvzsnc2f",
        "title": "Life OS",
        "description": "A self-hosted personal operating system that brings thirteen life domains, resilient gamification, learning tools, and long-running AI agents into one multi-platform product.",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1788340106571-zidws9v-lifeos.png",
        "type": "Full-stack product, AI, personal productivity",
        "openSourceDetails": {
          "link": null,
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": "https://game.bayesian-labs.com",
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmth6ypyd000juon6gfpstuwz",
        "title": "Company Landing Page",
        "description": "Landing Page for Tech Company",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1788340435321-wwsew65-Portfolio.png",
        "type": "Full Stack",
        "openSourceDetails": {
          "link": "https://github.com/anoopkarnik/company-landing-page",
          "npmPackageLink": "",
          "stars": "1",
          "weeklyDownloads": "69",
          "weeklyClones": "381"
        },
        "notionDetails": {
          "templateLink": "",
          "views": "0",
          "downloads": "0",
          "rating": "0"
        },
        "websiteDetails": {
          "websiteLink": "https://bayesian-labs.com",
          "websiteViews": "15",
          "websiteUsers": "0"
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": ""
        }
      },
      {
        "id": "cmthie9ae000huotq6pjonpww",
        "title": "SaaS Forge",
        "description": "An open-source, India-ready SaaS foundation for shipping web, desktop, and mobile products without surrendering the code, infrastructure, or upgrade path.",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1788340505200-i6knnm6-boilerplate.png",
        "type": "Open-source SaaS platform",
        "openSourceDetails": {
          "link": "https://github.com/anoopkarnik/saas-forge",
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": "https://boilerplate.bayesian-labs.com",
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": "https://youtu.be/0zpQTtcsPtk?si=Lx5FZdsYd1CL_Dlt"
        }
      },
      {
        "id": "cmthie91u0007uotqo2760zl4",
        "title": "HRS Hikers Website",
        "description": "Created a Website for a Hiking and Camping company, with my cousin. It is currently just informational on what the company does. I maintain their website, and do some updates and the only reason I do it for free is it is for a cousin, who handles my insurances and sometimes finances.",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1788348557972-celxv4m-hrshikers.png",
        "type": "Full Stack",
        "openSourceDetails": {
          "link": "https://github.com/anoopkarnik/hrshikers",
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": "https://hrshikers.com/",
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmthie94n0009uotq4qaci70e",
        "title": "Financial Documents OCR",
        "description": "Bloomberg Screenshot → Structured Data Pipeline (Next.js + n8n + Textract + PaddleOCR) I built an end-to-end automation that converts raw Bloomberg Terminal screenshots into clean, structured financial tables — fully automated, fully deployed. Users upload screenshots through a Next.js frontend (Vercel). Each upload tr",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/portfolio/financial-documents-ocr-21bae9db0a.png",
        "type": "n8n Automation, Full Stack, AI",
        "openSourceDetails": {
          "link": "https://github.com/anoopkarnik/image-to-ocr-app",
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": null,
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmthie97j000duotqzzpnsqd6",
        "title": "Google Analytics and Search Report Generation",
        "description": "📈 Automated GA4 Analytics Reporting Engine (Parent + Sub-Workflow System) (n8n · GA4 · QuickChart · Google Docs · OpenRouter Agents) I built a modular analytics automation system using n8n, consisting of a master workflow and a suite of specialized sub-workflows. Together, they generate clean, visual, and insight-read",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/portfolio/google-analytics-and-search-report-generation-064b27f24c.png",
        "type": "n8n Automation, AI",
        "openSourceDetails": {
          "link": null,
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": null,
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmthie991000fuotqgv10q8pv",
        "title": "Restaurant Order Vapi Call",
        "description": "🍕 Voice-Driven AI Ordering System (Vapi + n8n + Google Sheets) A fully automated conversational ordering pipeline powered by real-time menu validation, backend tool orchestration, and structured order writing. I built a complete voice-based restaurant ordering system that connects a Vapi voice AI agent with a multi-st",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/portfolio/restaurant-order-vapi-call-5b81a70924.png",
        "type": "n8n Automation, AI",
        "openSourceDetails": {
          "link": null,
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": null,
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmthie9bv000juotqfyjipo2j",
        "title": "Portfolio Boilerplate",
        "description": "A Modern, Minimal Developer Portfolio Built with Next.js & Notion(Powered by Turborepo) with AI Assistant 🔹 Easily customizable 🔹 Supports Notion as CMS 🔹 Deploy with Vercel in one click 👉 Live Demo⭐ If you find this project useful, consider giving it a star to support development!📌 Overview Every developer needs",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1788352323861-pz300wv-PortfolioBoilerplate.png",
        "type": "Full Stack",
        "openSourceDetails": {
          "link": "https://github.com/anoopkarnik/MyPortfolio",
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": "https://anoopkarnik.net",
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmthie9d6000luotqdqhbukb0",
        "title": "Fhir Data Validation Service",
        "description": "Created a Flask Service which consumers raw fhir data from a kafka topic and checks against fhir resource fields based on profiles created in what is present and what is not present in each record for each resource.",
        "demoImage": "https://raw.githubusercontent.com/anoopkarnik/react-tailwind-portfolio/main/src/assets/images/project-covers/validation.png",
        "type": "Data Engineering",
        "openSourceDetails": {
          "link": null,
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": null,
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      },
      {
        "id": "cmthie9g1000puotqr212bi3h",
        "title": "Git Grasp",
        "description": "🚀 Git Grasp Git Grasp is an AI-powered web-app that transforms any GitHub repository into a personalized, structured learning journey—complete with quizzes, level-based syllabuses, and grasp tracking. 💡 Designed to reduce ramp-up time for engineers joining new teams, projects, or open source communities. --- 🔍 What",
        "demoImage": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/portfolio/git-grasp-b6aa2308da.png",
        "type": "Full Stack, AI",
        "openSourceDetails": {
          "link": "https://github.com/anoopkarnik/git-grasp",
          "npmPackageLink": null,
          "stars": "",
          "weeklyDownloads": "",
          "weeklyClones": ""
        },
        "notionDetails": {
          "templateLink": null,
          "views": "",
          "downloads": "",
          "rating": ""
        },
        "websiteDetails": {
          "websiteLink": "https://gitgrasp.bayesian-labs.com/landing",
          "websiteViews": "",
          "websiteUsers": ""
        },
        "contentDetails": {
          "blogLink": "",
          "videoLink": null
        }
      }
    ]
  },
  "testimonialSection": {
    "heading": "Discover Why People Use These Company Products\n",
    "description": "These are some of the testimonials that we have received from our clients.\n",
    "testimonials": [
      {
        "id": "cmth6yq2z000nuon63eeogi9d",
        "name": "Lucia Fernandez",
        "userName": "Lucia Fernandez",
        "position": "Product Engineer, CloudBotics\n",
        "comment": "This boilerplate has opinions—and they’re good ones. Tailwind, NextAuth, Prisma, all wired up beautifully. Like a golden retriever with Docker skills.\n",
        "image": ""
      },
      {
        "id": "cmth6yq55000puon6xkldvwjx",
        "name": "Eli Cohen",
        "userName": "Eli Cohen",
        "position": "Tech Lead, Velocity Apps\n",
        "comment": "We built our MVP in 9 days instead of 30. The GitHub Actions alone are worth it. Anoop, please take my money again.”\n",
        "image": ""
      },
      {
        "id": "cmth6yq68000ruon6azi5kftu",
        "name": "Daniel Rivera",
        "userName": "Daniel Rivera",
        "position": "CTO, QuickLaunchAI\n",
        "comment": "We used to start each SaaS project with chaos and coffee. Now we just use this boilerplate. Still use the coffee, though.\n",
        "image": ""
      },
      {
        "id": "cmth6yq7d000tuon68b5weq7h",
        "name": "James “CodeNoob” Nguyen",
        "userName": "James “CodeNoob” Nguyen",
        "position": "Indie Hacker\n",
        "comment": "It turned my ‘idea graveyard’ into actual live products. This is the indie hacker's Excalibur.\n",
        "image": ""
      },
      {
        "id": "cmth6yq8n000vuon64erdzakp",
        "name": "Isabella Rossi",
        "userName": "Isabella Rossi",
        "position": "UX Engineer, Launchmatic\n",
        "comment": "I actually enjoyed setting up a SaaS product for once. That’s saying something. The starter even made the login page look good by default.\n",
        "image": ""
      },
      {
        "id": "cmth6yq9r000xuon6w4kxwjge",
        "name": "Marcus Deane",
        "userName": "Marcus Deane",
        "position": "VP of Engineering, NovaStack\n",
        "comment": "Using this boilerplate felt like cheating. And I’m totally okay with that. Enterprise-grade structure in under 10 minutes.\n",
        "image": ""
      },
      {
        "id": "cmth6yqav000zuon64eerty0w",
        "name": "Sarah Lin",
        "userName": "Sarah Lin",
        "position": "Founder of FinPilot\n",
        "comment": "This boilerplate saved me three weeks and possibly a mild burnout. From auth to payments, everything just… worked. I might name my next dog after it.\n",
        "image": ""
      },
      {
        "id": "cmth6yqby0011uon6414jc0cy",
        "name": "Anoop Karnik",
        "userName": "Anoop Karnik",
        "position": "Founder of Bayesian Labs\n",
        "comment": "Better than any other free boilerplate code in the market for a SaaS product\n",
        "image": "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1774436085185-z8jsbxx-d28afb4411234c61a7899ac281fd10fe.jpg"
      },
      {
        "id": "cmth6yqd10013uon6fgxiuaxf",
        "name": "Kavya Sharma",
        "userName": "Kavya Sharma",
        "position": "Full-Stack Developer, Freelance\n",
        "comment": "Honestly, I was skeptical at first. But the folder structure, the CI/CD setup, the modular auth—chef’s kiss. This is not a boilerplate, it’s a launchpad.\n",
        "image": ""
      },
      {
        "id": "cmth6yqeb0015uon6u085duzm",
        "name": "Omkar jain",
        "userName": "Omkar jain",
        "position": "Developer Advocate, SaaSFoundry\n",
        "comment": "Every part of the stack felt thought-through. This isn’t just code—it’s wisdom in YAML and TypeScript.\n",
        "image": ""
      }
    ]
  },
  "teamSection": {
    "heading": "Our Dedicated Crew\n",
    "description": "Some of the best people in the industry are working with us, as we are the only ones in the industry of spontaneous product development.\n",
    "teamList": [
      {
        "id": "cmth6yqhl0017uon6pmlvdv42",
        "name": "Anoop Karnik Dasika",
        "position": "Founder\n",
        "description": "Just into creating Sci-Fi stuff. Currently working on automation and gamifying the boring stuff, we do in life.\n",
        "imageUrl": "/anoop.jpg",
        "socialNetworks": [
          {
            "name": "Youtube",
            "url": "https://www.youtube.com/@bayesianlabs"
          },
          {
            "name": "Github",
            "url": "https://github.com/anoopkarnik"
          },
          {
            "name": "Twitter",
            "url": "https://x.com/anooplegend1992"
          },
          {
            "name": "Instagram",
            "url": "https://www.instagram.com/anoopkarnik"
          },
          {
            "name": "Facebook",
            "url": "https://www.facebook.com/anoop.karnik1"
          },
          {
            "name": "Linkedin",
            "url": "https://www.linkedin.com/in/anoopkarnik/"
          }
        ]
      }
    ]
  },
  "footerSection": {
    "title": "Bayesian Labs",
    "logo": "/logo.png",
    "darkLogo": "/logo.png",
    "creator": "Bayesian Labs\n",
    "creatorLink": "https://anoopkarnik.net",
    "footerList": [
      {
        "id": "cmth6yqm60019uon68z76c57x",
        "label": "Terms & Conditions",
        "href": "/legal/terms-of-service",
        "type": "Legal"
      },
      {
        "id": "cmth6yqoc001buon6mnkb7zhi",
        "label": "Github",
        "href": "https://github.com/anoopkarnik",
        "type": "Follow Us"
      },
      {
        "id": "cmth6yqpp001duon60fxzks4y",
        "label": "Youtube",
        "href": "https://youtube.com/@bayesianlabs",
        "type": "Follow Us"
      },
      {
        "id": "cmth6yqqs001fuon6k84c459y",
        "label": "Cancellation/Refund Policies",
        "href": "/legal/cancellation-refund-policies",
        "type": "Legal"
      },
      {
        "id": "cmth6yqrw001huon6ny0jakr3",
        "label": "Privacy Policy",
        "href": "/legal/privacy-policy",
        "type": "Legal"
      },
      {
        "id": "cmth6yqsz001juon6qnctqijy",
        "label": "Contact Us",
        "href": "/legal/contact-us",
        "type": "Legal"
      },
      {
        "id": "cmth6yqu3001luon6b0wyb5wb",
        "label": "Twitter",
        "href": "https://x.com/anoopbayesian",
        "type": "Follow Us"
      },
      {
        "id": "cmth6yqvd001nuon6h70nggom",
        "label": "Linkedin",
        "href": "https://www.linkedin.com/in/anoopkarnik/",
        "type": "Follow Us"
      }
    ]
  },
  "cancellationRefundPolicies": {
    "supportEmailAddress": "support@bayesian-labs.com\n",
    "siteName": "Bayesian Labs",
    "companyLegalName": "Bayesian Labs (OPC) Private Limited\n",
    "websiteUrl": "https://bayesian-labs.com\n",
    "lastUpdated": "2025-12-01\n"
  },
  "privacyPolicy": {
    "supportEmailAddress": "support@bayesian-labs.com\n",
    "siteName": "Bayesian Labs",
    "companyLegalName": "Bayesian Labs (OPC) Private Limited\n",
    "country": "India\n",
    "websiteUrl": "https://bayesian-labs.com\n",
    "lastUpdated": "2025-12-01\n"
  },
  "contactUs": {
    "supportEmailAddress": "support@bayesian-labs.com\n",
    "companyLegalName": "Bayesian Labs (OPC) Private Limited\n",
    "lastUpdated": "2025-12-01\n",
    "contactNumber": "+918919450356\n",
    "address": "B2, 2nd Floor, Maruthi Enclave, Domalguda, Hyderabad, Telangana, Hyderabad\n"
  },
  "termsOfService": {
    "supportEmailAddress": "support@bayesian-labs.com\n",
    "siteName": "Bayesian Labs",
    "companyLegalName": "Bayesian Labs (OPC) Private Limited\n",
    "country": "India\n",
    "websiteUrl": "https://bayesian-labs.com\n",
    "lastUpdated": "2025-12-01\n",
    "version": "v1\n",
    "address": "B2, 2nd Floor, Maruthi Enclave, Domalguda, Hyderabad, Telangana, Hyderabad\n"
  },
  "newsletterSection": {
    "heading": "Subscribe to our Newsletter",
    "description": "Stay updated with our latest features and releases.",
    "supportEmailAddress": "support@bayesian-labs.com\n"
  }
};
