/* eslint-disable */
/*
 * Generated by `pnpm --filter web sync:cms-constants`.
 * Do not edit this file by hand. Admin/CMS changes should be synced by rerunning the command.
 */

export const landingPageSnapshotSyncedAt = "2026-06-13T11:13:04.063Z";

export const landingPageSnapshot: any = {
  navbarSection: {
    title: "Bayesian Labs",
    logo: "/logo.png",
    darkLogo: "/logo.png",
    githubLink: "https://github.com/anoopkarnik/company-landing-page",
    githubUsername: "anoopkarnik",
    githubRepositoryName: "company-landing-page",
    donateNowLink:
      "https://checkout.dodopayments.com/buy/pdt_rU5SMAMbi7zEpRXWX8mJa?quantity=1&redirect_url=https://bayesian-labs.com",
  },
  heroSection: {
    tagline: "Gamifying and Automating your Life and Business\n",
    description:
      "Gamifying and Automating your life and business using Open Source Projects, Micro SaaS Projects, Notion Templates and AI\n",
    appointmentLink:
      "https://calendly.com/anoop-karnik-bayesian-labs/discovery-call",
  },
  aboutSection: {
    heading: "About",
    companyDetails:
      "Bayesian Labs s a solopreneur-driven company specializing in Notion templates, open-source projects, and Micro SaaS products. Our mission is to bring automation and AI-driven efficiency to both businesses and individuals. We take ideas from concept to production—building small-scale projects (those that can be completed in under a month) from scratch with speed and quality. Each member of our team wears multiple hats, combining the expertise of a Project Manager, Full-Stack Developer, UI/UX Designer, QA Engineer, and DevOps Engineer. While we may not have the hyper-specialization of a dedicated team in each role, our depth of knowledge across these areas ensures timely execution with high-quality results. projects - from scratch to production. Each person part of the company has skills of a project manager, full stack developer, UI/UX designer, QA Engineer and Devops engineer. Our breadth in each of the above areas is not as good as a specialist but depth in each area is good enough to get the job done in a timely manner with quality.\n",
    users: 148,
    subscribers: 16,
    products: 16,
    downloads: 2500,
  },
  serviceSection: {
    heading: "Client-Centric Services\n",
    description:
      "These are some of the services that I offer to my clients. I am always looking to improve and add more services\n",
    services: [
      {
        id: "2ff1d3fa-a0a0-8140-bae5-e502b6781720",
        title: "n8n Workflows",
        description:
          "The support modules consists of documentation, newsletter to subscribe, send mail to our support and booking a discovery call with us using resend for mails and n8n workflows for ai assistant\n",
        imageUrl: "",
      },
      {
        id: "2ff1d3fa-a0a0-814f-a530-de019d62cadd",
        title: "Notion Template Creation",
        description:
          "The CMS Module use notion databases  through api and upstash redis for cache to get all data in landing pages\n",
        imageUrl: "",
      },
      {
        id: "2ff1d3fa-a0a0-8176-82a7-e13a44227b47",
        title: "MVP Develpment",
        description:
          "Landing Page Module consists of landing page with various sections (navbar, hero, feature, faq, pricing, footer), legal pages (contact us, cancellations & refund policies, privacy policy, terms & conditions). All these pages use shadcn, aceternity and custom components, blocks and themes.\n",
        imageUrl: "",
      },
      {
        id: "2ff1d3fa-a0a0-8110-a332-f1bae7849926",
        title: "AI Integration",
        description:
          "A high-performance build system for SaaS Web Apps, which can be deployed immediately to vercel after just filling the environment variables\n",
        imageUrl: "",
      },
    ],
  },
  projectSection: {
    heading: "Many Great Products\n",
    description:
      "These are some of the products that we have build. We are always looking to improve and add more products\n",
    projects: [
      {
        id: "2ff1d3fa-a0a0-809b-8296-ed8c9632cbaf",
        title: "Personal Productivity System",
        description:
          "This is a template to maintain all my relationships - friends, family, acquantances and professional. If you want to have any kind of permanent relationship in your life, you need to maintain contact based on long term emotions irrespective of what your short term emotions say. It also categorises your social needs based on Dunbar's Number Framework and Maslow's Hierarchy of Needs which determine a person's social fulfillment in life.\n",
        demoImage: "",
        type: "Notion Template",
        openSourceDetails: {
          link: null,
          stars: null,
          weeklyDownloads: null,
          weeklyClones: null,
        },
        notionDetails: {
          templateLink:
            "https://www.notion.so/templates/personal-productivity-system-143",
          views: 12,
          downloads: 5,
          rating: null,
        },
        websiteDetails: {
          websiteLink: null,
          websiteViews: null,
        },
        contentDetails: {
          blogLink: "",
          videoLink: null,
        },
      },
      {
        id: "2ff1d3fa-a0a0-808f-9f58-dee356079501",
        title: "Social & Relationship System",
        description:
          "This is a template to maintain all my relationships - friends, family, acquantances and professional. If you want to have any kind of permanent relationship in your life, you need to maintain contact based on long term emotions irrespective of what your short term emotions say. It also categorises your social needs based on Dunbar's Number Framework and Maslow's Hierarchy of Needs which determine a person's social fulfillment in life.\n",
        demoImage: "",
        type: "Notion Template",
        openSourceDetails: {
          link: null,
          stars: null,
          weeklyDownloads: null,
          weeklyClones: null,
        },
        notionDetails: {
          templateLink:
            "https://www.notion.so/templates/social-relationship-system",
          views: 22,
          downloads: 10,
          rating: null,
        },
        websiteDetails: {
          websiteLink: null,
          websiteViews: null,
        },
        contentDetails: {
          blogLink: "",
          videoLink: "https://youtu.be/NeISUZa87EE",
        },
      },
      {
        id: "2ff1d3fa-a0a0-8015-a6b4-e915ea90c139",
        title: "Solopreneur Projects Dashboard",
        description:
          "This dashboard is perfect for planning production level projects which a very small team or solopreneur builds, it includes databases for projects, sprints, bugs, features, team, etc. The buttons only work for paid notion subscribers but the template functions perfectly without those too. Feel free to leave reviews and any additions you think would work well for you. I will reply back once a week to all those queries to inform if it is possible in notion or not and if it is add the feature.\n",
        demoImage: "",
        type: "Notion Template",
        openSourceDetails: {
          link: null,
          stars: null,
          weeklyDownloads: null,
          weeklyClones: null,
        },
        notionDetails: {
          templateLink:
            "https://www.notion.so/templates/solopreneur-projects-dashboard",
          views: 84,
          downloads: 24,
          rating: 5,
        },
        websiteDetails: {
          websiteLink: null,
          websiteViews: null,
        },
        contentDetails: {
          blogLink: "",
          videoLink: "https://youtu.be/_t6RJ9Trw6A",
        },
      },
      {
        id: "2ff1d3fa-a0a0-8057-b106-fe1e93d6e694",
        title: "Personal Finance System",
        description:
          "This dashboard is used to put your monthly budgets, yearly budgets, assets and liabilities, financial transactions, FIRE and funds with a sample list of all budgets a person above 25 faces. You get to know based on your expenses, income, inflation, death age, current age, lifestyle adjustment, increment, etc your time to bankruptcy or FIRE, and all other things like that\n",
        demoImage: "",
        type: "Notion Template",
        openSourceDetails: {
          link: null,
          stars: null,
          weeklyDownloads: null,
          weeklyClones: null,
        },
        notionDetails: {
          templateLink:
            "https://www.notion.so/templates/personal-finance-system",
          views: 6,
          downloads: 4,
          rating: 5,
        },
        websiteDetails: {
          websiteLink: null,
          websiteViews: null,
        },
        contentDetails: {
          blogLink: "",
          videoLink: "https://youtu.be/jOASverE_FI",
        },
      },
      {
        id: "2ff1d3fa-a0a0-803f-9daa-c97fbdac6f98",
        title: "Portfolio Boilerplate",
        description: "The best portfolio boilerplate code for a developer.\n",
        demoImage: "",
        type: "Full Stack",
        openSourceDetails: {
          link: "https://github.com/anoopkarnik/portfolio-boilerplate",
          stars: 1,
          weeklyDownloads: 381,
          weeklyClones: 69,
        },
        notionDetails: {
          templateLink: null,
          views: null,
          downloads: null,
          rating: null,
        },
        websiteDetails: {
          websiteLink: "https://anoopkarnik.net",
          websiteViews: 15,
        },
        contentDetails: {
          blogLink: "",
          videoLink: null,
        },
      },
      {
        id: "2ff1d3fa-a0a0-80da-8ccd-e7abb3df923b",
        title: "Company Landing Page",
        description: "Landing Page for Tech Company\n",
        demoImage: "",
        type: "Full Stack",
        openSourceDetails: {
          link: "https://github.com/anoopkarnik/company-landing-page",
          stars: 1,
          weeklyDownloads: 69,
          weeklyClones: 381,
        },
        notionDetails: {
          templateLink: null,
          views: null,
          downloads: null,
          rating: null,
        },
        websiteDetails: {
          websiteLink: "https://bayesian-labs.com",
          websiteViews: 15,
        },
        contentDetails: {
          blogLink: "",
          videoLink: null,
        },
      },
      {
        id: "2ff1d3fa-a0a0-8044-b10e-f65084863917",
        title: "SaaS Forge",
        description:
          "These are some of the services that I offer to my clients. I am always looking to improve and add more services\n",
        demoImage: "",
        type: "Full Stack",
        openSourceDetails: {
          link: "https://github.com/anoopkarnik/turborepo-saas-boilerplate-code",
          stars: 7,
          weeklyDownloads: 3,
          weeklyClones: 13,
        },
        notionDetails: {
          templateLink: null,
          views: null,
          downloads: null,
          rating: null,
        },
        websiteDetails: {
          websiteLink: "https://boilerplate.bayesian-labs.com",
          websiteViews: 213,
        },
        contentDetails: {
          blogLink: "",
          videoLink: null,
        },
      },
    ],
  },
  testimonialSection: {
    heading: "Discover Why People Use These Company Products\n",
    description:
      "These are some of the testimonials that we have received from our clients.\n",
    testimonials: [
      {
        id: "2ff1d3fa-a0a0-8113-a695-c41194cdaf55",
        name: "Lucia Fernandez",
        userName: "Lucia Fernandez",
        position: "Product Engineer, CloudBotics\n",
        comment:
          "This boilerplate has opinions—and they’re good ones. Tailwind, NextAuth, Prisma, all wired up beautifully. Like a golden retriever with Docker skills.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-8167-ba52-cfaa7d4fb029",
        name: "Eli Cohen",
        userName: "Eli Cohen",
        position: "Tech Lead, Velocity Apps\n",
        comment:
          "We built our MVP in 9 days instead of 30. The GitHub Actions alone are worth it. Anoop, please take my money again.”\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-81a5-b4e5-d0882fc684e3",
        name: "Daniel Rivera",
        userName: "Daniel Rivera",
        position: "CTO, QuickLaunchAI\n",
        comment:
          "We used to start each SaaS project with chaos and coffee. Now we just use this boilerplate. Still use the coffee, though.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-81b2-b3e4-e1f30eac54ed",
        name: "James “CodeNoob” Nguyen",
        userName: "James “CodeNoob” Nguyen",
        position: "Indie Hacker\n",
        comment:
          "It turned my ‘idea graveyard’ into actual live products. This is the indie hacker's Excalibur.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-81e8-af48-c80fbf565e6d",
        name: "Isabella Rossi",
        userName: "Isabella Rossi",
        position: "UX Engineer, Launchmatic\n",
        comment:
          "I actually enjoyed setting up a SaaS product for once. That’s saying something. The starter even made the login page look good by default.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-8123-8a39-d4e8e199fe66",
        name: "Marcus Deane",
        userName: "Marcus Deane",
        position: "VP of Engineering, NovaStack\n",
        comment:
          "Using this boilerplate felt like cheating. And I’m totally okay with that. Enterprise-grade structure in under 10 minutes.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-8139-b389-eef1fb35262f",
        name: "Sarah Lin",
        userName: "Sarah Lin",
        position: "Founder of FinPilot\n",
        comment:
          "This boilerplate saved me three weeks and possibly a mild burnout. From auth to payments, everything just… worked. I might name my next dog after it.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-8140-9a1f-d2dc69f778af",
        name: "Anoop Karnik",
        userName: "Anoop Karnik",
        position: "Founder of Bayesian Labs\n",
        comment:
          "Better than any other free boilerplate code in the market for a SaaS product\n",
        image:
          "https://pub-540add8b8ece44cab4963a5fe4abbf37.r2.dev/cms-images/1774436085185-z8jsbxx-d28afb4411234c61a7899ac281fd10fe.jpg",
      },
      {
        id: "2ff1d3fa-a0a0-8149-aeea-e66b25ebc68d",
        name: "Kavya Sharma",
        userName: "Kavya Sharma",
        position: "Full-Stack Developer, Freelance\n",
        comment:
          "Honestly, I was skeptical at first. But the folder structure, the CI/CD setup, the modular auth—chef’s kiss. This is not a boilerplate, it’s a launchpad.\n",
        image: "",
      },
      {
        id: "2ff1d3fa-a0a0-8158-8ec2-fb597772da09",
        name: "Omkar jain",
        userName: "Omkar jain",
        position: "Developer Advocate, SaaSFoundry\n",
        comment:
          "Every part of the stack felt thought-through. This isn’t just code—it’s wisdom in YAML and TypeScript.\n",
        image: "",
      },
    ],
  },
  teamSection: {
    heading: "Our Dedicated Crew\n",
    description:
      "Some of the best people in the industry are working with us, as we are the only ones in the industry of spontaneous product development.\n",
    teamList: [
      {
        id: "2ff1d3fa-a0a0-80c1-bf74-de5ef73af792",
        name: "Anoop Karnik Dasika",
        position: "Founder\n",
        description:
          "Just into creating Sci-Fi stuff. Currently working on automation and gamifying the boring stuff, we do in life.\n",
        imageUrl: "/anoop.jpg",
        socialNetworks: [
          {
            name: "Youtube",
            url: "https://www.youtube.com/@bayesianlabs",
          },
          {
            name: "Github",
            url: "https://github.com/anoopkarnik",
          },
          {
            name: "Twitter",
            url: "https://x.com/anooplegend1992",
          },
          {
            name: "Instagram",
            url: "https://www.instagram.com/anoopkarnik",
          },
          {
            name: "Facebook",
            url: "https://www.facebook.com/anoop.karnik1",
          },
          {
            name: "Linkedin",
            url: "https://www.linkedin.com/in/anoopkarnik/",
          },
        ],
      },
    ],
  },
  footerSection: {
    title: "Bayesian Labs",
    logo: "/logo.png",
    darkLogo: "/logo.png",
    creator: "Bayesian Labs\n",
    creatorLink: "https://anoopkarnik.net",
    footerList: [
      {
        id: "2ff1d3fa-a0a0-8103-b428-c45a825ea4f7",
        label: "Terms & Conditions",
        href: "/legal/terms-of-service",
        type: "Legal",
      },
      {
        id: "2ff1d3fa-a0a0-810d-840e-fd7e9e7ea4be",
        label: "Github",
        href: "https://github.com/anoopkarnik",
        type: "Follow Us",
      },
      {
        id: "2ff1d3fa-a0a0-8168-9fc5-f15038c5e58b",
        label: "Youtube",
        href: "https://youtube.com/@bayesianlabs",
        type: "Follow Us",
      },
      {
        id: "2ff1d3fa-a0a0-8194-a41a-f2d91d9b2cd0",
        label: "Cancellation/Refund Policies",
        href: "/legal/cancellation-refund-policies",
        type: "Legal",
      },
      {
        id: "2ff1d3fa-a0a0-8197-af2f-dcdbc1312f72",
        label: "Privacy Policy",
        href: "/legal/privacy-policy",
        type: "Legal",
      },
      {
        id: "2ff1d3fa-a0a0-819d-9ecc-c9f714746f49",
        label: "Contact Us",
        href: "/legal/contact-us",
        type: "Legal",
      },
      {
        id: "2ff1d3fa-a0a0-81cf-9d3a-c4531cd82bde",
        label: "Twitter",
        href: "https://x.com/anoopbayesian",
        type: "Follow Us",
      },
      {
        id: "2ff1d3fa-a0a0-81c3-8c12-d44cdceb454c",
        label: "Linkedin",
        href: "https://www.linkedin.com/in/anoopkarnik/",
        type: "Follow Us",
      },
    ],
  },
  cancellationRefundPolicies: {
    supportEmailAddress: "support@bayesian-labs.com\n",
    siteName: "Bayesian Labs",
    companyLegalName: "Bayesian Labs (OPC) Private Limited\n",
    websiteUrl: "https://bayesian-labs.com\n",
    lastUpdated: "2025-12-01\n",
  },
  privacyPolicy: {
    supportEmailAddress: "support@bayesian-labs.com\n",
    siteName: "Bayesian Labs",
    companyLegalName: "Bayesian Labs (OPC) Private Limited\n",
    country: "India\n",
    websiteUrl: "https://bayesian-labs.com\n",
    lastUpdated: "2025-12-01\n",
  },
  contactUs: {
    supportEmailAddress: "support@bayesian-labs.com\n",
    companyLegalName: "Bayesian Labs (OPC) Private Limited\n",
    lastUpdated: "2025-12-01\n",
    contactNumber: "+918919450356\n",
    address:
      "B2, 2nd Floor, Maruthi Enclave, Domalguda, Hyderabad, Telangana, Hyderabad\n",
  },
  termsOfService: {
    supportEmailAddress: "support@bayesian-labs.com\n",
    siteName: "Bayesian Labs",
    companyLegalName: "Bayesian Labs (OPC) Private Limited\n",
    country: "India\n",
    websiteUrl: "https://bayesian-labs.com\n",
    lastUpdated: "2025-12-01\n",
    version: "v1\n",
    address:
      "B2, 2nd Floor, Maruthi Enclave, Domalguda, Hyderabad, Telangana, Hyderabad\n",
  },
  newsletterSection: {
    heading: "Subscribe to our Newsletter",
    description: "Stay updated with our latest features and releases.",
    supportEmailAddress: "support@bayesian-labs.com\n",
  },
};
